name: TheBohoCeo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55982
title: An Entrepreneur on a Mision.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffff3f'
    - '#ff1770'
    - '#00a18a'
    - '#6b16a7'
    - '#d0b26d'
  brandStrength: 0.18850036757066846
  lightness: 0.3153579190839082
  saturation: 0.5051234418060631
  rhythmicContrast: 0.9939261234831065
purpose: []
