name: TheBohoCeo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55982
title: An Entrepreneur on a Mission.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffff3f'
    - '#ff1770'
    - '#00a18a'
    - '#6b16a7'
    - '#d0b26d'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
